//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArActionTurn : ArAction {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArActionTurn(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArActionTurn_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArActionTurn obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArActionTurn() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArActionTurn(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArActionTurn(string name, double speedStartTurn, double speedFullTurn, double turnAmount) : this(AriaCSPINVOKE.new_ArActionTurn__SWIG_0(name, speedStartTurn, speedFullTurn, turnAmount), true) {
  }

  public ArActionTurn(string name, double speedStartTurn, double speedFullTurn) : this(AriaCSPINVOKE.new_ArActionTurn__SWIG_1(name, speedStartTurn, speedFullTurn), true) {
  }

  public ArActionTurn(string name, double speedStartTurn) : this(AriaCSPINVOKE.new_ArActionTurn__SWIG_2(name, speedStartTurn), true) {
  }

  public ArActionTurn(string name) : this(AriaCSPINVOKE.new_ArActionTurn__SWIG_3(name), true) {
  }

  public ArActionTurn() : this(AriaCSPINVOKE.new_ArActionTurn__SWIG_4(), true) {
  }

  public override ArActionDesired fire(ArActionDesired currentDesired) {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArActionTurn_fire(swigCPtr, ArActionDesired.getCPtr(currentDesired));
    ArActionDesired ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArActionDesired(cPtr, false);
    if (AriaCSPINVOKE.SWIGPendingException.Pending) throw AriaCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override ArActionDesired getDesired() {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArActionTurn_getDesired(swigCPtr);
    ArActionDesired ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArActionDesired(cPtr, false);
    return ret;
  }

}

}
