//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArActionGroupStop : ArActionGroup {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArActionGroupStop(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArActionGroupStop_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArActionGroupStop obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArActionGroupStop() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArActionGroupStop(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArActionGroupStop(ArRobot robot) : this(AriaCSPINVOKE.new_ArActionGroupStop(ArRobot.getCPtr(robot)), true) {
  }

  public ArActionStop getActionStop() {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArActionGroupStop_getActionStop(swigCPtr);
    ArActionStop ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArActionStop(cPtr, false);
    return ret;
  }

  public ArActionStop myActionStop {
    set {
      AriaCSPINVOKE.ArActionGroupStop_myActionStop_set(swigCPtr, ArActionStop.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = AriaCSPINVOKE.ArActionGroupStop_myActionStop_get(swigCPtr);
      ArActionStop ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArActionStop(cPtr, false);
      return ret;
    } 
  }

}

}
