//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArActionStallRecover : ArAction {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArActionStallRecover(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArActionStallRecover_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArActionStallRecover obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArActionStallRecover() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArActionStallRecover(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArActionStallRecover(string name, double obstacleDistance, int cyclesToMove, double speed, double degreesToTurn, bool enabled) : this(AriaCSPINVOKE.new_ArActionStallRecover__SWIG_0(name, obstacleDistance, cyclesToMove, speed, degreesToTurn, enabled), true) {
  }

  public ArActionStallRecover(string name, double obstacleDistance, int cyclesToMove, double speed, double degreesToTurn) : this(AriaCSPINVOKE.new_ArActionStallRecover__SWIG_1(name, obstacleDistance, cyclesToMove, speed, degreesToTurn), true) {
  }

  public ArActionStallRecover(string name, double obstacleDistance, int cyclesToMove, double speed) : this(AriaCSPINVOKE.new_ArActionStallRecover__SWIG_2(name, obstacleDistance, cyclesToMove, speed), true) {
  }

  public ArActionStallRecover(string name, double obstacleDistance, int cyclesToMove) : this(AriaCSPINVOKE.new_ArActionStallRecover__SWIG_3(name, obstacleDistance, cyclesToMove), true) {
  }

  public ArActionStallRecover(string name, double obstacleDistance) : this(AriaCSPINVOKE.new_ArActionStallRecover__SWIG_4(name, obstacleDistance), true) {
  }

  public ArActionStallRecover(string name) : this(AriaCSPINVOKE.new_ArActionStallRecover__SWIG_5(name), true) {
  }

  public ArActionStallRecover() : this(AriaCSPINVOKE.new_ArActionStallRecover__SWIG_6(), true) {
  }

  public override ArActionDesired fire(ArActionDesired currentDesired) {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArActionStallRecover_fire(swigCPtr, ArActionDesired.getCPtr(currentDesired));
    ArActionDesired ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArActionDesired(cPtr, false);
    if (AriaCSPINVOKE.SWIGPendingException.Pending) throw AriaCSPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override ArActionDesired getDesired() {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArActionStallRecover_getDesired(swigCPtr);
    ArActionDesired ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArActionDesired(cPtr, false);
    return ret;
  }

  public void addToConfig(ArConfig config, string sectionName, ArPriority.Priority priority) {
    AriaCSPINVOKE.ArActionStallRecover_addToConfig__SWIG_0(swigCPtr, ArConfig.getCPtr(config), sectionName, (int)priority);
  }

  public void addToConfig(ArConfig config, string sectionName) {
    AriaCSPINVOKE.ArActionStallRecover_addToConfig__SWIG_1(swigCPtr, ArConfig.getCPtr(config), sectionName);
  }

  public override void activate() {
    AriaCSPINVOKE.ArActionStallRecover_activate(swigCPtr);
  }

}

}
