//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArASyncTask : ArThread {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArASyncTask(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArASyncTask_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArASyncTask obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArASyncTask() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArASyncTask(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public virtual SWIGTYPE_p_void runThread(SWIGTYPE_p_void arg) {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArASyncTask_runThread(swigCPtr, SWIGTYPE_p_void.getCPtr(arg));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public virtual void run() {
    AriaCSPINVOKE.ArASyncTask_run(swigCPtr);
  }

  public virtual void runAsync() {
    AriaCSPINVOKE.ArASyncTask_runAsync(swigCPtr);
  }

  public override void stopRunning() {
    AriaCSPINVOKE.ArASyncTask_stopRunning(swigCPtr);
  }

  public virtual int create(bool joinable, bool lowerPriority) {
    int ret = AriaCSPINVOKE.ArASyncTask_create__SWIG_0(swigCPtr, joinable, lowerPriority);
    return ret;
  }

  public virtual int create(bool joinable) {
    int ret = AriaCSPINVOKE.ArASyncTask_create__SWIG_1(swigCPtr, joinable);
    return ret;
  }

  public virtual int create() {
    int ret = AriaCSPINVOKE.ArASyncTask_create__SWIG_2(swigCPtr);
    return ret;
  }

  public virtual SWIGTYPE_p_void runInThisThread(SWIGTYPE_p_void arg) {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArASyncTask_runInThisThread__SWIG_0(swigCPtr, SWIGTYPE_p_void.getCPtr(arg));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public virtual SWIGTYPE_p_void runInThisThread() {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArASyncTask_runInThisThread__SWIG_1(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public override string getThreadActivity() {
    string ret = AriaCSPINVOKE.ArASyncTask_getThreadActivity(swigCPtr);
    return ret;
  }

}

}
