//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArCallbackList : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ArCallbackList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArCallbackList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArCallbackList() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArCallbackList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ArCallbackList(string name, ArLog.LogLevel logLevel, bool singleShot) : this(AriaCSPINVOKE.new_ArCallbackList__SWIG_0(name, (int)logLevel, singleShot), true) {
  }

  public ArCallbackList(string name, ArLog.LogLevel logLevel) : this(AriaCSPINVOKE.new_ArCallbackList__SWIG_1(name, (int)logLevel), true) {
  }

  public ArCallbackList(string name) : this(AriaCSPINVOKE.new_ArCallbackList__SWIG_2(name), true) {
  }

  public ArCallbackList() : this(AriaCSPINVOKE.new_ArCallbackList__SWIG_3(), true) {
  }

  public void invoke() {
    AriaCSPINVOKE.ArCallbackList_invoke(swigCPtr);
  }

}

}
