//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArCompassConnector : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ArCompassConnector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArCompassConnector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArCompassConnector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArCompassConnector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ArCompassConnector(ArArgumentParser argParser) : this(AriaCSPINVOKE.new_ArCompassConnector(ArArgumentParser.getCPtr(argParser)), true) {
  }

  public ArTCM2 create(ArRobot robot) {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArCompassConnector_create(swigCPtr, ArRobot.getCPtr(robot));
    ArTCM2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArTCM2(cPtr, false);
    return ret;
  }

  public bool connect(ArTCM2 arg0) {
    bool ret = AriaCSPINVOKE.ArCompassConnector_connect(swigCPtr, ArTCM2.getCPtr(arg0));
    return ret;
  }

}

}
