//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArConfigArg_Double : ArConfigArg {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArConfigArg_Double(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArConfigArg_Double_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArConfigArg_Double obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArConfigArg_Double() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArConfigArg_Double(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArConfigArg_Double(string name, double d, string desc, double min, double max) : this(AriaCSPINVOKE.new_ArConfigArg_Double__SWIG_0(name, d, desc, min, max), true) {
  }

  public ArConfigArg_Double(string name, double d, string desc, double min) : this(AriaCSPINVOKE.new_ArConfigArg_Double__SWIG_1(name, d, desc, min), true) {
  }

  public ArConfigArg_Double(string name, double d, string desc) : this(AriaCSPINVOKE.new_ArConfigArg_Double__SWIG_2(name, d, desc), true) {
  }

  public ArConfigArg_Double(string name, double d) : this(AriaCSPINVOKE.new_ArConfigArg_Double__SWIG_3(name, d), true) {
  }

}

}
