//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArDPPTUPacket : ArBasePacket {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArDPPTUPacket(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArDPPTUPacket_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArDPPTUPacket obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArDPPTUPacket() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArDPPTUPacket(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArDPPTUPacket(ushort bufferSize) : this(AriaCSPINVOKE.new_ArDPPTUPacket__SWIG_0(bufferSize), true) {
  }

  public ArDPPTUPacket() : this(AriaCSPINVOKE.new_ArDPPTUPacket__SWIG_1(), true) {
  }

  public virtual void byte2ToBuf(int val) {
    AriaCSPINVOKE.ArDPPTUPacket_byte2ToBuf(swigCPtr, val);
  }

  public override void finalizePacket() {
    AriaCSPINVOKE.ArDPPTUPacket_finalizePacket(swigCPtr);
  }

}

}
