//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class AriaCS {
  public static void md5_init(md5_state_t pms) {
    AriaCSPINVOKE.md5_init(md5_state_t.getCPtr(pms));
  }

  public static void md5_append(md5_state_t pms, SWIGTYPE_p_unsigned_char data, int nbytes) {
    AriaCSPINVOKE.md5_append(md5_state_t.getCPtr(pms), SWIGTYPE_p_unsigned_char.getCPtr(data), nbytes);
  }

  public static void md5_finish(md5_state_t pms, SWIGTYPE_p_unsigned_char digest) {
    AriaCSPINVOKE.md5_finish(md5_state_t.getCPtr(pms), SWIGTYPE_p_unsigned_char.getCPtr(digest));
  }

  public static readonly int ENABLE_FUNCTOR_DIRECTORS = AriaCSPINVOKE.ENABLE_FUNCTOR_DIRECTORS_get();
  public static readonly int _GNU_SOURCE = AriaCSPINVOKE._GNU_SOURCE_get();
  public static readonly double M_PI = AriaCSPINVOKE.M_PI_get();
  public static readonly string ARMAP_DEFAULT_SCAN_TYPE = AriaCSPINVOKE.ARMAP_DEFAULT_SCAN_TYPE_get();
  public static readonly string ARTCM2_DEFAULT_SERIAL_PORT = AriaCSPINVOKE.ARTCM2_DEFAULT_SERIAL_PORT_get();
  public static readonly int MAX_RESPONSE_BYTES = AriaCSPINVOKE.MAX_RESPONSE_BYTES_get();
  public static readonly int BIDIRECTIONAL_TIMEOUT = AriaCSPINVOKE.BIDIRECTIONAL_TIMEOUT_get();
  public static readonly int UNIDIRECTIONAL_TIMEOUT = AriaCSPINVOKE.UNIDIRECTIONAL_TIMEOUT_get();
  public static readonly int AUTO_UPDATE_TIME = AriaCSPINVOKE.AUTO_UPDATE_TIME_get();
  public static readonly double TOLERANCE = AriaCSPINVOKE.TOLERANCE_get();
}

}
