//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArIRs : ArRangeDevice {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArIRs(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArIRs_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArIRs obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArIRs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArIRs(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArIRs(uint currentBufferSize, uint cumulativeBufferSize, string name, int maxSecondsToKeepCurrent) : this(AriaCSPINVOKE.new_ArIRs__SWIG_0(currentBufferSize, cumulativeBufferSize, name, maxSecondsToKeepCurrent), true) {
  }

  public ArIRs(uint currentBufferSize, uint cumulativeBufferSize, string name) : this(AriaCSPINVOKE.new_ArIRs__SWIG_1(currentBufferSize, cumulativeBufferSize, name), true) {
  }

  public ArIRs(uint currentBufferSize, uint cumulativeBufferSize) : this(AriaCSPINVOKE.new_ArIRs__SWIG_2(currentBufferSize, cumulativeBufferSize), true) {
  }

  public ArIRs(uint currentBufferSize) : this(AriaCSPINVOKE.new_ArIRs__SWIG_3(currentBufferSize), true) {
  }

  public ArIRs() : this(AriaCSPINVOKE.new_ArIRs__SWIG_4(), true) {
  }

  public override void setRobot(ArRobot robot) {
    AriaCSPINVOKE.ArIRs_setRobot(swigCPtr, ArRobot.getCPtr(robot));
  }

  public void processReadings() {
    AriaCSPINVOKE.ArIRs_processReadings(swigCPtr);
  }

}

}
