//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArIrrfDevice : ArRangeDevice {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArIrrfDevice(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArIrrfDevice_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArIrrfDevice obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArIrrfDevice() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArIrrfDevice(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArIrrfDevice(uint currentBufferSize, uint cumulativeBufferSize, string name) : this(AriaCSPINVOKE.new_ArIrrfDevice__SWIG_0(currentBufferSize, cumulativeBufferSize, name), true) {
  }

  public ArIrrfDevice(uint currentBufferSize, uint cumulativeBufferSize) : this(AriaCSPINVOKE.new_ArIrrfDevice__SWIG_1(currentBufferSize, cumulativeBufferSize), true) {
  }

  public ArIrrfDevice(uint currentBufferSize) : this(AriaCSPINVOKE.new_ArIrrfDevice__SWIG_2(currentBufferSize), true) {
  }

  public ArIrrfDevice() : this(AriaCSPINVOKE.new_ArIrrfDevice__SWIG_3(), true) {
  }

  public bool packetHandler(ArRobotPacket packet) {
    bool ret = AriaCSPINVOKE.ArIrrfDevice_packetHandler(swigCPtr, ArRobotPacket.getCPtr(packet));
    return ret;
  }

  public void setCumulativeMaxRange(double r) {
    AriaCSPINVOKE.ArIrrfDevice_setCumulativeMaxRange(swigCPtr, r);
  }

  public override void setRobot(ArRobot arg0) {
    AriaCSPINVOKE.ArIrrfDevice_setRobot(swigCPtr, ArRobot.getCPtr(arg0));
  }

}

}
