//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArMD5Calculator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ArMD5Calculator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArMD5Calculator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArMD5Calculator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArMD5Calculator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static void toDisplay(SWIGTYPE_p_unsigned_char digestBuf, uint digestLength, string displayBuf, uint displayLength) {
    AriaCSPINVOKE.ArMD5Calculator_toDisplay(SWIGTYPE_p_unsigned_char.getCPtr(digestBuf), digestLength, displayBuf, displayLength);
  }

  public static bool calculateChecksum(string fileName, SWIGTYPE_p_unsigned_char md5DigestBuffer, uint md5DigestBufferLen) {
    bool ret = AriaCSPINVOKE.ArMD5Calculator_calculateChecksum(fileName, SWIGTYPE_p_unsigned_char.getCPtr(md5DigestBuffer), md5DigestBufferLen);
    return ret;
  }

  public ArMD5Calculator(ArFunctor1_CString secondFunctor) : this(AriaCSPINVOKE.new_ArMD5Calculator__SWIG_0(ArFunctor1_CString.getCPtr(secondFunctor)), true) {
  }

  public ArMD5Calculator() : this(AriaCSPINVOKE.new_ArMD5Calculator__SWIG_1(), true) {
  }

  public void reset() {
    AriaCSPINVOKE.ArMD5Calculator_reset(swigCPtr);
  }

  public void append(string str) {
    AriaCSPINVOKE.ArMD5Calculator_append(swigCPtr, str);
  }

  public SWIGTYPE_p_unsigned_char getDigest() {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArMD5Calculator_getDigest(swigCPtr);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public ArFunctor1_CString getFunctor() {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArMD5Calculator_getFunctor(swigCPtr);
    ArFunctor1_CString ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArFunctor1_CString(cPtr, false);
    return ret;
  }

  public ArFunctor1_CString getSecondFunctor() {
    global::System.IntPtr cPtr = AriaCSPINVOKE.ArMD5Calculator_getSecondFunctor(swigCPtr);
    ArFunctor1_CString ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArFunctor1_CString(cPtr, false);
    return ret;
  }

  public void setSecondFunctor(ArFunctor1_CString secondFunctor) {
    AriaCSPINVOKE.ArMD5Calculator_setSecondFunctor(swigCPtr, ArFunctor1_CString.getCPtr(secondFunctor));
  }

  public static readonly int DIGEST_LENGTH = AriaCSPINVOKE.ArMD5Calculator_DIGEST_LENGTH_get();
  public static readonly int DISPLAY_LENGTH = AriaCSPINVOKE.ArMD5Calculator_DISPLAY_LENGTH_get();

}

}
