//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArModeTCM2 : ArMode {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArModeTCM2(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArModeTCM2_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArModeTCM2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArModeTCM2() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArModeTCM2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArModeTCM2(ArRobot robot, string name, char key, char key2, ArTCM2 tcm2) : this(AriaCSPINVOKE.new_ArModeTCM2__SWIG_0(ArRobot.getCPtr(robot), name, key, key2, ArTCM2.getCPtr(tcm2)), true) {
  }

  public ArModeTCM2(ArRobot robot, string name, char key, char key2) : this(AriaCSPINVOKE.new_ArModeTCM2__SWIG_1(ArRobot.getCPtr(robot), name, key, key2), true) {
  }

  public override void activate() {
    AriaCSPINVOKE.ArModeTCM2_activate(swigCPtr);
  }

  public override void deactivate() {
    AriaCSPINVOKE.ArModeTCM2_deactivate(swigCPtr);
  }

  public override void help() {
    AriaCSPINVOKE.ArModeTCM2_help(swigCPtr);
  }

  public override void userTask() {
    AriaCSPINVOKE.ArModeTCM2_userTask(swigCPtr);
  }

}

}
