//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArRootMeanSquareCalculator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ArRootMeanSquareCalculator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArRootMeanSquareCalculator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArRootMeanSquareCalculator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArRootMeanSquareCalculator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ArRootMeanSquareCalculator() : this(AriaCSPINVOKE.new_ArRootMeanSquareCalculator(), true) {
  }

  public double getRootMeanSquare() {
    double ret = AriaCSPINVOKE.ArRootMeanSquareCalculator_getRootMeanSquare(swigCPtr);
    return ret;
  }

  public void add(int val) {
    AriaCSPINVOKE.ArRootMeanSquareCalculator_add(swigCPtr, val);
  }

  public void clear() {
    AriaCSPINVOKE.ArRootMeanSquareCalculator_clear(swigCPtr);
  }

  public void setName(string name) {
    AriaCSPINVOKE.ArRootMeanSquareCalculator_setName(swigCPtr, name);
  }

  public string getName() {
    string ret = AriaCSPINVOKE.ArRootMeanSquareCalculator_getName(swigCPtr);
    return ret;
  }

  public uint getCurrentNumAveraged() {
    uint ret = AriaCSPINVOKE.ArRootMeanSquareCalculator_getCurrentNumAveraged(swigCPtr);
    return ret;
  }

}

}
