//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArTrimbleGPS : ArGPS {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public ArTrimbleGPS(global::System.IntPtr cPtr, bool cMemoryOwn) : base(AriaCSPINVOKE.ArTrimbleGPS_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArTrimbleGPS obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArTrimbleGPS() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArTrimbleGPS(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ArTrimbleGPS() : this(AriaCSPINVOKE.new_ArTrimbleGPS(), true) {
  }

  public bool sendTSIPCommand(char command, string data, uint dataLen) {
    bool ret = AriaCSPINVOKE.ArTrimbleGPS_sendTSIPCommand(swigCPtr, command, data, dataLen);
    return ret;
  }

}

}
