//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class ArVCC4Commands : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ArVCC4Commands(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ArVCC4Commands obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ArVCC4Commands() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AriaCSPINVOKE.delete_ArVCC4Commands(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ArVCC4Commands() : this(AriaCSPINVOKE.new_ArVCC4Commands(), true) {
  }

  public enum Command {
    DELIM = 0x00,
    DEVICEID = 0x30,
    PANSLEW = 0x50,
    TILTSLEW = 0x51,
    STOP = 0x53,
    INIT = 0x58,
    SLEWREQ = 0x59,
    ANGLEREQ = 0x5c,
    PANTILT = 0x62,
    SETRANGE = 0x64,
    PANTILTREQ = 0x63,
    INFRARED = 0x76,
    PRODUCTNAME = 0x87,
    LEDCONTROL = 0x8E,
    CONTROL = 0x90,
    POWER = 0xA0,
    AUTOFOCUS = 0xA1,
    ZOOMSTOP = 0xA2,
    GAIN = 0xA5,
    FOCUS = 0xB0,
    ZOOM = 0xB3,
    ZOOMREQ = 0xB4,
    IRCUTFILTER = 0xB5,
    DIGITALZOOM = 0xB7,
    FOOTER = 0xEF,
    RESPONSE = 0xFE,
    HEADER = 0xFF
  }

}

}
