//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace AriaCS {

public class SWIGTYPE_p_ArFunctor1T_double_t {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public SWIGTYPE_p_ArFunctor1T_double_t(global::System.IntPtr cPtr, bool futureUse) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public SWIGTYPE_p_ArFunctor1T_double_t() {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(SWIGTYPE_p_ArFunctor1T_double_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }
}

}
